# Generated by Django 5.0.14 on 2025-07-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_globalemailsetting_useremailpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailPreference',
        ),
    ]
