# Generated by Django 5.0.14 on 2025-07-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
