# Generated by Django 5.0.14 on 2025-07-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_client_is_internal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='is_internal',
        ),
    ]
