# Generated by Django 5.0.14 on 2025-07-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_client_is_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
