# Generated by Django 5.0.14 on 2025-07-10 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ticketapproval_delete_ticketreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketapproval',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='core.ticket'),
        ),
    ]
