# Generated by Django 5.0.14 on 2025-07-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_ticketapproval_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketapproval',
            name='approver',
        ),
    ]
