# Generated by Django 5.0.14 on 2025-07-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_ticketapproval_approver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketApproval',
        ),
    ]
