# Generated by Django 5.0.14 on 2025-07-15 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_emaillog_messagethread_delete_globalemailsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Ticket Management System', max_length=100)),
                ('system_logo', models.ImageField(blank=True, null=True, upload_to='system_logos/')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10)),
                ('default_priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('default_status', models.CharField(choices=[('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('working_hours', models.CharField(default='09:00 - 17:00', max_length=30)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(default='d/m/Y', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', max_length=20)),
                ('password_policy', models.CharField(choices=[('standard', 'Standard'), ('strong', 'Strong'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('notify_on_assignment', models.BooleanField(default=True)),
                ('notify_on_completion', models.BooleanField(default=True)),
                ('notify_on_status_change', models.BooleanField(default=True)),
                ('notify_on_approval', models.BooleanField(default=True)),
                ('notify_on_rejection', models.BooleanField(default=True)),
                ('notify_on_reassignment', models.BooleanField(default=True)),
                ('notify_on_employee_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
