# Generated by Django 5.2.4 on 2025-07-21 10:28

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_systemsetting_emailnotificationsetting'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
    ]
